-- 코드를 입력하세요
SELECT BT.CATEGORY, SUM(BT.SALES) AS TOTAL_SALES
  FROM (
        SELECT BS.BOOK_ID, B.CATEGORY, BS.SALES_DATE, BS.SALES
          FROM BOOK_SALES AS BS
          LEFT JOIN BOOK AS B
            ON BS.BOOK_ID = B.BOOK_ID
         WHERE BS.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
  ) AS BT
 GROUP BY BT.CATEGORY
 ORDER BY CATEGORY;
